language: c
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
    - GAP_PKGS_TO_BUILD="io profiling orb cvec"

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - libgmp-dev:i386
    - libreadline-dev:i386
    - gcc-multilib
    - g++-multilib

matrix:
  include:
    - env: CFLAGS="-O2" CC=clang CXX=clang++
      compiler: clang
    - env: CFLAGS="-O2"
      compiler: gcc
    - env: CFLAGS="-O2" HPCGAP=yes GAP_PKGS_TO_BUILD="io orb cvec"
      compiler: gcc
    - env: CFLAGS="-O2" HPCGAP=yes SUITE=statistics GAP_PKGS_TO_BUILD="io orb cvec"
      compiler: gcc

branches:
  except:
    - gh-pages

before_script:
  - export GAPROOT="$HOME/gap"
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)

 
notifications:
  slack: lbfm:Ed9IneWr1EgUpjuskzKZELDU 
 
