name: GaussPar
version: 0.1.0
date: 2020-12-16
description: |
    Parallel Gaussian elimination for finite fields.

authors:
    - name: Jendrik Brachter
      url: mailto:brachter@cs.uni-kl.de
    - name: Sergio Siccha
      url: mailto:siccha@mathematik.uni-kl.de
    - name: Emma Ahrens
      url: mailto:emma.ahrens@rwth-aachen.de

maintainers:
    - name: Jendrik Brachter
      url: mailto:brachter@cs.uni-kl.de
    - name: Sergio Siccha
      url: mailto:siccha@mathematik.uni-kl.de

GAP: "4.8"

www: https://github.com/lbfm-rwth/GaussPar/
readme: README.md
packageinfo: https://github.com/lbfm-rwth/GaussPar/

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/example/releases/download/v4.2.1/Example-4.2.1.tar.gz
github: https://github.com/lbfm-rwth/GaussPar/

abstract: TODO.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
