name: GaussPar
version: 0.1.0
date: 2020-12-16
description: |
    Parallel Gaussian algorithm for finite fields.

authors:
    - name: Jendrik Brachter
      url: brachter@cs.uni-kl.de
    - name: Sergio Siccha
      url: siccha@mathematik.uni-kl.de
    - name: Emma Ahrens
      url: emma.ahrens@rwth-aachen.de

maintainers:
    - name: Jendrik Brachter
      url: brachter@cs.uni-kl.de
    - name: Sergio Siccha
      url: siccha@mathematik.uni-kl.de

GAP: "4.8"

needed-pkgs:
    - name: none.

www: https://github.com/lbfm-rwth/GaussPar/
readme: README.md
packageinfo: https://github.com/lbfm-rwth/GaussPar/

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/example/releases/download/v4.2.1/Example-4.2.1.tar.gz

abstract: TODO.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
